CREATE TABLE IF NOT EXISTS employee_details (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  gender VARCHAR(50),
  email VARCHAR(255),
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
